Improve auto-approval workflow with job status check and timeout handling

diff --git a/.github/workflows/reusable-auto-approve.yaml b/.github/workflows/reusable-auto-approve.yaml
--- a/.github/workflows/reusable-auto-approve.yaml
+++ b/.github/workflows/reusable-auto-approve.yaml
@@ -1,4 +1,3 @@
----
 name: reusable-auto-approve
 on:
   workflow_call:
@@ -11,7 +10,7 @@ jobs:
     steps:
       - name: Generate token
         id: generate_token
-        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a  # v.2.1.0
+        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v.2.1.0
         with:
           app_id: ${{ secrets.GH_APP_ID }}
           private_key: ${{ secrets.GH_APP_PEM_FILE }}
@@ -21,6 +20,21 @@ jobs:
           gh auth setup-git
       - name: approve workflow run only if
         run: |-
+          #  loop to wait for jobs to start
+          i=0
+          for (( i=0; i<3; ++i )); do
+            echo "$i, looking for job to autoapprove"
+            if [[ "$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs --jq '.jobs[] | select(.status == "waiting").name')" == *"plan / plan" ]] ; then
+              break
+            else
+              echo "sleeping"
+              sleep 5
+            fi
+          done
+          if [[ "$i" == "3" ]]; then
+            echo "::error:: autoapproval timed out"
+            exit 1
+          fi
           ENV_ID=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/pending_deployments --jq '.[].environment.id')
           echo "ENV_ID: ${ENV_ID}"
           ENV_NAME=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/pending_deployments --jq '.[].environment.name')
@@ -28,7 +42,7 @@ jobs:
           JOB_NAME=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs --jq '.jobs[] | select(.status == "waiting").name')
           echo "JOB_NAME: ${JOB_NAME}"
           if [[ "$JOB_NAME" == *"plan / plan" ]] ; then
-            echo "auto approving this job, since its a plan (I hope!) "
+            echo "auto approving this job, since it looks like a plan "
             RESULT=$(gh api --verbose repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/pending_deployments --method POST -F "environment_ids[]=${ENV_ID}" -f "state=approved" -f "comment=Autoapproved since its a plan")
             echo "done, this is how it went: $RESULT"
           else
