Update workflow trigger name and adapt quotes in workflow steps.- Change trigger name to use double quotes- Update single quotes to double quotes in workflow step names

diff --git a/.github/workflows/trigger.yaml b/.github/workflows/trigger.yaml
--- a/.github/workflows/trigger.yaml
+++ b/.github/workflows/trigger.yaml
@@ -1,6 +1,6 @@
 # Entrypoint for github actions
 
-name: 'trigger'
+name: "trigger"
 
 on:
   pull_request:
@@ -10,7 +10,7 @@ jobs:
   detect:
     # This is to identify which terraform root modules was changed (if any)
     runs-on: ubuntu-latest
-    name: 'Detect terraform changes'
+    name: "Detect terraform changes"
     outputs:
       directories: ${{ steps.condense.outputs.result }}
       release-type: ${{ steps.check_pr_label.outputs.release-type}}
@@ -21,114 +21,112 @@ jobs:
     steps:
       # I'm getting the labels from the API and not the context("contains(github.event.pull_request.labels.*.name, 'Env Promote')") as the labels
       # are added in 2nd API call so they aren't included in the PR context
-    - name: Check PR labels
-      id: check_pr_label
-      env:
-        PR_URL: ${{github.event.pull_request.html_url}}
-          #GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
-        GH_TOKEN: ${{ github.token }}
-      run: |
-        LABELS=$(gh pr view $PR_URL --json labels  --jq '.labels[]| select ((.name=="dev") or (.name=="test") or (.name=="prod")) |.name')
-        NUMBER_OF_LABELS=$(echo "$LABELS" |wc -w)
-        if [ "$NUMBER_OF_LABELS" -eq "0" ] ; then
-          echo "::error ::No release type labels found (dev/test/prod)"
-          exit 1
-        fi
-        case "$LABELS" in
-          *prod*)
-            echo "release-type=prod" >> $GITHUB_OUTPUT
-            exit 0
-            ;;
-          *test*)
-            echo "release-type=test" >> $GITHUB_OUTPUT
-            exit 0
-            ;;
-          *dev*)
-            echo "release-type=dev" >> $GITHUB_OUTPUT
-            exit 0
-            ;;
-        esac
+      - name: Check PR labels
+        id: check_pr_label
+        env:
+          PR_URL:
+            ${{github.event.pull_request.html_url}}
+            #GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          LABELS=$(gh pr view $PR_URL --json labels  --jq '.labels[]| select ((.name=="dev") or (.name=="test") or (.name=="prod")) |.name')
+          NUMBER_OF_LABELS=$(echo "$LABELS" |wc -w)
+          if [ "$NUMBER_OF_LABELS" -eq "0" ] ; then
+            echo "::error ::No release type labels found (dev/test/prod)"
+            exit 1
+          fi
+          case "$LABELS" in
+            *prod*)
+              echo "release-type=prod" >> $GITHUB_OUTPUT
+              exit 0
+              ;;
+            *test*)
+              echo "release-type=test" >> $GITHUB_OUTPUT
+              exit 0
+              ;;
+            *dev*)
+              echo "release-type=dev" >> $GITHUB_OUTPUT
+              exit 0
+              ;;
+          esac
 
-         
-        #else
-        #  echo "release-type=${LABELS}" >> $GITHUB_OUTPUT
-        #fi
+      - name: Get changed files
+        uses: Ana06/get-changed-files@25f79e676e7ea1868813e21465014798211fad8c # v2.3.0
+        id: raw-files
+        with:
+          format: "json"
 
+      - name: Condense to directory list and match terraform directories (00.main, 01.network, 02.whatever etc..)
+        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
+        id: condense
+        env:
+          RAW_FILES: "${{ steps.raw-files.outputs.all }}"
+        with:
+          script: |
+            const raw = JSON.parse(process.env.RAW_FILES);
+            const directories = Array.from(new Set(raw
+              .filter(x => !x.startsWith('.'))                    // Filter out hidden paths
+              .filter(x => /^terraform\/\d{2}[^/]*\/?/.test(x))   // Adjust the regex to stop at the first directory under 'terraform'
+              .map(x => {
+                const matches = x.match(/^(terraform\/\d{2}[^/]*)\/?/);           // Use a match to extract the root directory including 'terraform'
+                return matches ? matches[1].replace(/^terraform\//, '') : null;   // Return the matched root directory or null if not matched
+              })
+              .filter(x => x !== null) // filter out null values
+            ));
+            if (directories.length < 1) return {};
+            return {
+              include: directories.map(directory => ({ directory })),
+            };
 
-    - name: Get changed files
-      uses: Ana06/get-changed-files@25f79e676e7ea1868813e21465014798211fad8c # v2.3.0
-      id: raw-files
-      with:
-        format: 'json'
+      - name: Dump github context
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+        shell: bash
+        run: |
+          echo "$GITHUB_CONTEXT"
 
-    - name: Condense to directory list and match terraform directories (00.main, 01.network, 02.whatever etc..)
-      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
-      id: condense
-      env:
-        RAW_FILES: '${{ steps.raw-files.outputs.all }}'
-      with:
-        script: |
-          const raw = JSON.parse(process.env.RAW_FILES);
-          const directories = Array.from(new Set(raw
-            .filter(x => !x.startsWith('.'))                    // Filter out hidden paths
-            .filter(x => /^terraform\/\d{2}[^/]*\/?/.test(x))   // Adjust the regex to stop at the first directory under 'terraform'
-            .map(x => {
-              const matches = x.match(/^(terraform\/\d{2}[^/]*)\/?/);           // Use a match to extract the root directory including 'terraform'
-              return matches ? matches[1].replace(/^terraform\//, '') : null;   // Return the matched root directory or null if not matched
-            })
-            .filter(x => x !== null) // filter out null values
-          ));
-          if (directories.length < 1) return {};
-          return {
-            include: directories.map(directory => ({ directory })),
-          }; 
+      - name: Modules to work on
+        run: echo ${{ steps.condense.outputs.result }}
 
-    - name: Dump github context
-      env:
-        GITHUB_CONTEXT: ${{ toJson(github) }}
-      shell: bash
-      run: |
-        echo "$GITHUB_CONTEXT"
-
-    - name: Modules to work on
-      run: echo ${{ steps.condense.outputs.result }}
-
-      #dev: 
-      #  if: contains(github.jobs.detect.outputs.release-type, 'dev')
-      #  needs: detect
-      #  strategy:
-      #    matrix: "${{ fromJson(needs.detect.outputs.directories) }}"
-      #    fail-fast: false
-      #  uses: ./.github/workflows/ci-runner.yaml
-      #  permissions: write-all
-      #  with:
-      #    environment: dev 
-      #    rootModule: ${{ matrix.directory }}
-    #if: contains(fromJson('["test"]'), github.jobs.detect.outputs.release-type) 
+        #dev:
+        #  if: contains(github.jobs.detect.outputs.release-type, 'dev')
+        #  needs: detect
+        #  strategy:
+        #    matrix: "${{ fromJson(needs.detect.outputs.directories) }}"
+        #    fail-fast: false
+        #  uses: ./.github/workflows/ci-runner.yaml
+        #  permissions: write-all
+        #  with:
+        #    environment: dev
+        #    rootModule: ${{ matrix.directory }}
+    #if: contains(fromJson('["test"]'), github.jobs.detect.outputs.release-type)
     #if: toJson(needs.jobs.outputs.directories) != '{}'
-      
 
-  ci:
+  ci-runner:
+    name: "CI Runner"
     needs: detect
+    runs-on: ubuntu-latest
     environment: ${{ needs.detect.outputs.release-type }}
     strategy:
       matrix: "${{ fromJson(needs.detect.outputs.directories) }}"
       fail-fast: false
-    uses: ./.github/workflows/reusable-ci.yaml
-    permissions: write-all
-    #with:
-    #  environment: ${{ needs.detect.outputs.release-type }}
-    #  rootModule: ${{ matrix.directory }}
-    #secrets: inherit
+    steps:
+      - name: "CI Runner"
+        uses: ./.github/workflows/ci-runner.yaml
+        permissions: write-all
+        with:
+          environment: ${{ needs.detect.outputs.release-type }}
+          rootModule: ${{ matrix.directory }}
+        secrets: inherit
 
-      #  prod:
-      #    if: contains(github.jobs.detect.outputs.release-type, 'dev')
-      #    needs: detect
-      #    strategy:
-      #      matrix: "${{ fromJson(needs.detect.outputs.directories) }}"
-      #      fail-fast: false
-      #    uses: ./.github/workflows/ci-runner.yaml
-      #    permissions: write-all
-      #    with:
-      #      environment: prod 
-      #      rootModule: ${{ matrix.directory }}
+    #  prod:
+    #    if: contains(github.jobs.detect.outputs.release-type, 'dev')
+    #    needs: detect
+    #    strategy:
+    #      matrix: "${{ fromJson(needs.detect.outputs.directories) }}"
+    #      fail-fast: false
+    #    uses: ./.github/workflows/ci-runner.yaml
+    #    permissions: write-all
+    #    with:
+    #      environment: prod
+    #      rootModule: ${{ matrix.directory }}
