Update trigger.yaml workflow with improved formatting and script execution

diff --git a/.github/workflows/trigger.yaml b/.github/workflows/trigger.yaml
--- a/.github/workflows/trigger.yaml
+++ b/.github/workflows/trigger.yaml
@@ -1,4 +1,5 @@
-name: trigger # Entrypoint for github actions
+---
+name: trigger  # Entrypoint for github actions
 on:
   pull_request:
     types: [opened, synchronize, reopened, labeled, unlabeled]
@@ -13,7 +14,6 @@ jobs:
       release-type: ${{ steps.check_pr_label.outputs.release-type}}
       is-merge-event: >-
         ${{ github.event_name == 'pull_request_target'
-
          && github.event.action == 'closed'
          && github.event.pull_request.merged == true }}
     steps:
@@ -25,14 +25,45 @@ jobs:
           PR_URL: ${{github.event.pull_request.html_url}}
           # GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
           GH_TOKEN: ${{ github.token }}
-        run: "# LABELS=$(gh pr view $PR_URL --json labels  --jq '.labels[]| select ((.name==\"test-deployed\") or (.name==\"test\") or (.name==\"prod\")) |.name')\nLABELS=$(gh api -H \"Accept: application/vnd.github+json\" /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/issues/${{ github.event.pull_request.number }}/labels | jq -r '.[]| select ((.name==\"test-deployed\") or (.name==\"test\") or (.name==\"prod\")) |.name')\nNUMBER_OF_LABELS=$(echo \"$LABELS\" |wc -w)\necho \"pull1: ${{ github.event.number }}\"\necho \"pull2: \" \nhest=$(echo \"$GITHUB_REF\" | awk -F / '{print $3}'\")\necho \"$hest\"\necho \"pull3: \"\nhest2=$(gh pr view --json number -q .number || echo \"\")\necho \"$hest2\"\necho \"pull4: ${{ github.event.pull_request.number }}\"\necho \"pull5: ${{ github.event.issue.number }}\"\nif [ \"$NUMBER_OF_LABELS\" -eq \"0\" ] ; then\n  echo \"::error ::No release type labels found (dev/test/prod)\"\n  exit 1\nfi\ncase \"$LABELS\" in\n  *prod*)\n    echo \"release-type=prod\" >> $GITHUB_OUTPUT\n# exit 0\n    ;;\n  *test*)\n    echo \"release-type=test\" >> $GITHUB_OUTPUT\n#    exit 0\n    ;;\n  *test-deployed*)\n    echo \"release-type=test-deployed\" >> $GITHUB_OUTPUT\n#    exit 0\n    ;;\nesac\n"
+        run: |
+          # LABELS=$(gh pr view $PR_URL --json labels  --jq '.labels[]| select ((.name=="test-deployed") or (.name=="test") or (.name=="prod")) |.name')
+          LABELS=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/issues/${{ github.event.pull_request.number }}/labels | jq -r '.[]| select ((.name=="test-deployed") or (.name=="test") or (.name=="prod")) |.name')
+          NUMBER_OF_LABELS=$(echo "$LABELS" |wc -w)
+          echo "pull1: ${{ github.event.number }}"
+          echo "pull2: "
+          hest=$(echo "$GITHUB_REF | awk -F / '{print $3}'")
+          echo "$hest"
+          echo "pull3: "
+          hest2=$(gh pr view --json number -q .number || echo "")
+          echo "$hest2"
+          echo "pull4: ${{ github.event.pull_request.number }}"
+          echo "pull5: ${{ github.event.issue.number }}"
+          if [ "$NUMBER_OF_LABELS" -eq "0" ] ; then
+            echo "::error ::No release type labels found (dev/test/prod)"
+            exit 1
+          fi
+          case "$LABELS" in
+            *prod*)
+              echo "release-type=prod" >> $GITHUB_OUTPUT
+          # exit 0
+              ;;
+            *test*)
+              echo "release-type=test" >> $GITHUB_OUTPUT
+          #    exit 0
+              ;;
+            *test-deployed*)
+              echo "release-type=test-deployed" >> $GITHUB_OUTPUT
+          #    exit 0
+              ;;
+          esac
       - name: Get changed files
-        uses: Ana06/get-changed-files@25f79e676e7ea1868813e21465014798211fad8c # v2.3.0
+        uses: Ana06/get-changed-files@25f79e676e7ea1868813e21465014798211fad8c  # v2.3.0
         id: raw-files
         with:
           format: json
-      - name: Condense to directory list and match terraform directories (00.main, 01.network, 02.whatever etc..)
-        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
+      - name: Condense to directory list and match terraform directories (00.main,
+          01.network, 02.whatever etc..)
+        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea  # v7.0.1
         id: condense
         env:
           RAW_FILES: ${{ steps.raw-files.outputs.all }}
